(******************************************************************************)
(*                                                                            *)
(* Copyright (c) 2026 Epure Team                                              *)
(* All rights reserved.                                                       *)
(*                                                                            *)
(******************************************************************************)

(** Always-on structural guards for the credential-gated CBL-08 E2E proof. *)

open Cabal

let contains text needle =
  let text_length = String.length text in
  let needle_length = String.length needle in
  let rec loop offset =
    if offset + needle_length > text_length then false
    else if String.sub text offset needle_length = needle then true
    else loop (offset + 1)
  in
  needle_length = 0 || loop 0

let index_of text needle =
  let text_length = String.length text in
  let needle_length = String.length needle in
  let rec loop offset =
    if offset + needle_length > text_length then None
    else if String.sub text offset needle_length = needle then Some offset
    else loop (offset + 1)
  in
  if needle_length = 0 then Some 0 else loop 0

let read_file path =
  let channel = open_in_bin path in
  Fun.protect
    ~finally:(fun () -> close_in_noerr channel)
    (fun () -> really_input_string channel (in_channel_length channel))

let read_test_file name =
  if Sys.file_exists name then read_file name
  else read_file (Filename.concat "test" name)

let test_capability_driven_selection () =
  let descriptors = Backend_registry.all () in
  let media =
    E2e_harness_config.media_schema_descriptors ~descriptors ()
  in
  Alcotest.(check (list string))
    "current positive media/schema matrix"
    ["codex"]
    (List.map (fun (d : Backend_registry.descriptor) -> d.id) media) ;
  let codex =
    match media with
    | [descriptor] -> descriptor
    | _ -> Alcotest.fail "expected exactly one P0 media/schema descriptor"
  in
  Alcotest.(check bool)
    "Codex P0 includes PNG"
    true
    (List.mem Backend_types.Png
       codex.capabilities.media_support.media_types) ;
  Alcotest.(check bool)
    "Codex P0 includes JPEG"
    true
    (List.mem Backend_types.Jpeg
       codex.capabilities.media_support.media_types) ;
  Alcotest.(check bool)
    "Codex P0 uses native schema"
    true
    codex.capabilities.native_json_schema_output ;
  let installed_floor =
    match Backend_version.of_string "0.131.0" with
    | Ok version -> version
    | Error _ -> Alcotest.fail "test baseline is invalid"
  in
  let descriptor_baseline =
    match Backend_version.of_string codex.baseline_version with
    | Ok version -> version
    | Error _ -> Alcotest.fail "Codex descriptor baseline is invalid"
  in
  Alcotest.(check bool)
    "Codex media baseline is at least 0.131.0"
    true
    (Backend_version.compare descriptor_baseline installed_floor >= 0) ;
  Alcotest.(check int)
    "no current positive web descriptor"
    0
    (List.length (E2e_harness_config.web_descriptors ~descriptors ()))

let test_filter_and_model_env_are_credential_free () =
  let reads = ref [] in
  let getenv name =
    reads := name :: !reads ;
    match name with
    | "CABAL_E2E_BACKEND" -> Some " codex, claude-code "
    | "CABAL_E2E_MODEL_CODEX" -> None
    | _ -> None
  in
  let selected =
    E2e_harness_config.selected_media_schema_descriptors ~getenv
      ~descriptors:(Backend_registry.all ()) ()
  in
  ignore (E2e_harness_config.model_for_backend ~getenv "codex") ;
  Alcotest.(check (list string))
    "filter retains only capability-positive media/schema backends"
    ["codex"]
    (List.map (fun (d : Backend_registry.descriptor) -> d.id) selected) ;
  List.iter
    (fun name ->
      Alcotest.(check bool)
        "harness configuration never reads credential variables"
        true
        (name = "CABAL_E2E_BACKEND" || name = "CABAL_E2E_MODEL_CODEX"))
    !reads

let test_fixture_schema_and_semantic_marker () =
  let fixtures = Media_web_schema_fixture.all in
  Alcotest.(check int) "one PNG and one JPEG fixture" 2 (List.length fixtures) ;
  List.iter
    (fun (fixture : Media_web_schema_fixture.t) ->
      Alcotest.(check bool)
        "fixture is tiny"
        true
        (String.length fixture.bytes > 0 && String.length fixture.bytes < 20_000) ;
      Alcotest.(check string)
        "fixture digest matches generated bytes"
        fixture.attachment.sha256
        Digestif.SHA256.(to_hex (digest_string fixture.bytes)) ;
      Alcotest.(check int)
        "fixture size metadata matches generated bytes"
        fixture.attachment.size_bytes
        (String.length fixture.bytes) ;
      Alcotest.(check bool)
        "fixture path remains workspace-relative"
        true
        (Filename.is_relative fixture.attachment.path))
    fixtures ;
  let png =
    List.find
      (fun fixture -> fixture.Media_web_schema_fixture.attachment.media_type = Png)
      fixtures
  in
  let jpeg =
    List.find
      (fun fixture -> fixture.Media_web_schema_fixture.attachment.media_type = Jpeg)
      fixtures
  in
  Alcotest.(check string)
    "PNG magic"
    "\x89PNG\r\n\x1a\n"
    (String.sub png.bytes 0 8) ;
  Alcotest.(check string)
    "JPEG start marker"
    "\xff\xd8"
    (String.sub jpeg.bytes 0 2) ;
  Alcotest.(check string)
    "JPEG end marker"
    "\xff\xd9"
    (String.sub jpeg.bytes (String.length jpeg.bytes - 2) 2) ;
  Alcotest.(check string) "PNG content marker" "blue" png.expected_value ;
  Alcotest.(check string) "JPEG content marker" "red" jpeg.expected_value ;
  let expected = Media_web_schema_fixture.expected_document_text fixtures in
  (match
     Json_schema_validator.validate
       ~schema:(Media_web_schema_fixture.schema fixtures)
       ~document:expected
   with
  | Ok () -> ()
  | Error _ -> Alcotest.fail "expected image-derived document violates schema") ;
  (match Media_web_schema_fixture.validate_response fixtures expected with
  | Ok () -> ()
  | Error _ -> Alcotest.fail "expected image-derived response was rejected") ;
  let constant_but_wrong =
    {|{"png_dominant_color":"blue","jpeg_dominant_color":"blue"}|}
  in
  (match Media_web_schema_fixture.validate_response fixtures constant_but_wrong with
  | Error _ -> ()
  | Ok () -> Alcotest.fail "constant schema compliance bypassed image semantics")

let test_generated_fixtures_pass_central_input_validation () =
  let working_dir = Filename.temp_dir "cabal-cbl08-structure-" "" in
  Unix.chmod working_dir 0o700 ;
  Fun.protect
    ~finally:(fun () ->
      List.iter
        (fun (fixture : Media_web_schema_fixture.t) ->
          let path = Filename.concat working_dir fixture.attachment.path in
          if Sys.file_exists path then Sys.remove path)
        Media_web_schema_fixture.all ;
      Unix.rmdir working_dir)
    (fun () ->
      let attachments =
        Media_web_schema_fixture.materialize ~working_dir
          Media_web_schema_fixture.all
      in
      let spec =
        Backend_types.make_task_spec
          ~prompt:"structural fixture validation"
          ~working_dir
          ~attachments
          ~web_access:Web_disabled
          ~json_schema:
            (Media_web_schema_fixture.schema Media_web_schema_fixture.all)
          ()
      in
      let limits : Task_preflight.limits =
        {
          max_attachments = 2;
          max_file_size_bytes = 20_000;
          max_total_size_bytes = 40_000;
        }
      in
      match Task_preflight.validate_inputs ~limits spec with
      | Ok () -> ()
      | Error _ ->
          Alcotest.fail "generated fixtures failed central input validation")

let result_cost : Backend_types.cost =
  {
    tokens_input = Some 1;
    tokens_output = Some 1;
    cost_usd = None;
    cache_creation_input_tokens = None;
    cache_read_input_tokens = None;
  }

let event seq attempt payload : Task_event.t =
  {seq; attempt; timestamp = Float.of_int seq; payload}

let test_event_trace_contract () =
  let text = {|{"png_dominant_color":"blue","jpeg_dominant_color":"red"}|} in
  let result =
    Backend_types.make_task_result ~status:Success ~agent_text:text
      ~session_id:"opaque-session" ~cost:result_cost ()
  in
  let attempt : Backend_types.task_attempt =
    {
      number = 1;
      kind = Initial_attempt;
      result;
      attempt_elapsed = 1.0;
      schema_validation_error = None;
      delivery =
        {
          attachment_references = [];
          attachment_delivery = Upload_attachments;
          web_access_policy = Web_disabled;
        };
    }
  in
  let execution =
    Backend_types.make_task_execution ~final_result:result ~attempts:[attempt]
      ~cleanup_status:Cleanup_succeeded ()
  in
  let events =
    [
      event 0 0 Task_started;
      event 1 1 (Attempt_started Initial_attempt);
      event 2 1 (Session_id "opaque-session");
      event 3 1 (Agent_text_delta text);
      event 4 1 (Token_usage result_cost);
      event 5 1 (Attempt_finished Attempt_succeeded);
      event 6 1 (Terminal Succeeded);
    ]
  in
  let requirements =
    Media_web_schema_e2e_support.protocol_requirements_for_backend "codex"
  in
  (match
     Media_web_schema_e2e_support.validate_event_trace ~requirements execution
       events
   with
  | Ok () -> ()
  | Error _ -> Alcotest.fail "valid normalized event trace was rejected") ;
  let post_terminal = events @ [event 7 1 (Agent_text_delta "forbidden")] in
  (match
     Media_web_schema_e2e_support.validate_event_trace ~requirements execution
       post_terminal
   with
  | Error _ -> ()
  | Ok () -> Alcotest.fail "post-terminal event was accepted") ;
  let missing_finish =
    List.filter
      (fun event ->
        match event.Task_event.payload with Attempt_finished _ -> false | _ -> true)
      events
  in
  match
    Media_web_schema_e2e_support.validate_event_trace ~requirements execution
      missing_finish
  with
  | Error _ -> ()
  | Ok () -> Alcotest.fail "attempt start/finish disagreement was accepted"

let test_e2e_binary_is_credential_gated_and_sequential () =
  let dune = read_test_file "dune" in
  let source = read_test_file "test_media_web_schema_backends.ml" in
  List.iter
    (fun needle ->
      Alcotest.(check bool)
        ("dune contains " ^ needle)
        true
        (contains dune needle))
    [
      "(name test_media_web_schema_backends)";
      "(= %{env:CABAL_E2E_TESTS=0} 1)";
      "test_media_web_schema_backends.exe";
      "(run ./test_media_web_schema_backends.exe)";
    ] ;
  let require_index needle =
    match index_of dune needle with
    | Some index -> index
    | None -> Alcotest.fail ("missing dune E2E entry: " ^ needle)
  in
  let enforcer = require_index "(run ./test_demo_627.exe)" in
  let native = require_index "(run ./test_native_json_schema_backends.exe)" in
  let media = require_index "(run ./test_media_web_schema_backends.exe)" in
  Alcotest.(check bool)
    "@e2e runs existing prerequisites before media/schema"
    true
    (enforcer < native && native < media) ;
  let binary_stanza =
    match index_of dune "(name test_media_web_schema_backends)" with
    | None -> Alcotest.fail "missing media/schema E2E stanza"
    | Some offset ->
        let remainder = String.sub dune offset (String.length dune - offset) in
        let length =
          match index_of remainder "\n\n(test\n" with
          | Some length -> length
          | None -> String.length remainder
        in
        String.sub remainder 0 length
  in
  Alcotest.(check bool)
    "the media/schema binary itself is CABAL_E2E_TESTS-gated"
    true
    (contains binary_stanza
       "(enabled_if\n  (= %{env:CABAL_E2E_TESTS=0} 1))") ;
  let alias_stanza =
    match index_of dune "(rule\n (alias e2e)" with
    | None -> Alcotest.fail "missing named E2E alias"
    | Some offset -> String.sub dune offset (String.length dune - offset)
  in
  Alcotest.(check bool)
    "the named E2E alias is inert unless CABAL_E2E_TESTS=1"
    true
    (contains alias_stanza
       "(enabled_if\n  (= %{env:CABAL_E2E_TESTS=0} 1))") ;
  Alcotest.(check bool)
    "live proof uses hardened bootstrap"
    true
    (contains source "Runtime_bootstrap.Hardened_builtins") ;
  Alcotest.(check bool)
    "live proof uses the central task runtime"
    true
    (contains source "Task_runtime.start_task") ;
  Alcotest.(check bool)
    "live proof never invokes the low-level backend"
    false
    (contains source "Agentic_backend.run_task") ;
  Alcotest.(check bool)
    "live proof never invokes the low-level schema enforcer"
    false
    (contains source "Json_schema_enforcer.run_task") ;
  Alcotest.(check bool)
    "live proof has no credential environment contract"
    false
    (contains source "ACCESS_TOKEN" || contains source "API_KEY")

let () =
  Alcotest.run
    "CBL-08 structural E2E guards"
    [
      ( "selection",
        [
          Alcotest.test_case "capability-driven media/web matrix" `Quick
            test_capability_driven_selection;
          Alcotest.test_case "filter/model env are credential-free" `Quick
            test_filter_and_model_env_are_credential_free;
        ] );
      ( "fixtures and schema",
        [
          Alcotest.test_case "deterministic media-derived response" `Quick
            test_fixture_schema_and_semantic_marker;
          Alcotest.test_case "generated bytes pass central preflight" `Quick
            test_generated_fixtures_pass_central_input_validation;
        ] );
      ( "events",
        [
          Alcotest.test_case "terminal and attempts are consistent" `Quick
            test_event_trace_contract;
        ] );
      ( "gating",
        [
          Alcotest.test_case "authenticated binary stays outside standard CI"
            `Quick test_e2e_binary_is_credential_gated_and_sequential;
        ] );
    ]
