(******************************************************************************)
(*                                                                            *)
(* Copyright (c) 2026 Epure Team                                              *)
(* All rights reserved.                                                       *)
(*                                                                            *)
(******************************************************************************)

(** Agentic backend module type.

    This module type defines the interface that all agentic backends must
    implement. An agentic backend is an external tool (Claude Code, Copilot,
    Codex, etc.) that can execute tasks autonomously.

    {b MVP simplification:} This interface omits the [config]/[type t]/[create]
    pattern from DESIGN.md Section 6 in favor of a simpler stateless design.
    Backends are configured externally (via their own config files or
    environment). This can be extended to the full DESIGN.md interface when
    backend-specific configuration is needed.

    See DESIGN.md Section 6 "Agentic Backend Layer" for the full design. *)

open Backend_types

(** Result of validating backend project configuration generated by Épure. *)
type config_check_result =
  | Config_valid
      (** Generated/applied project config passed this backend's local or native
          validation checks. *)
  | Config_invalid of string
      (** Generated/applied project config failed validation.  The string is a
          human-readable diagnostic including any native stdout/stderr details
          available. *)
  | Config_check_unsupported of string
      (** No deterministic validation is available in the current environment.
          The string documents why the check was skipped. *)

(** {1 Module Type} *)

(** The signature that all agentic backends must implement. *)
module type S = sig
  (** Unique identifier for this backend (e.g., "claude-code", "copilot"). *)
  val id : string

  (** Human-readable name for this backend (e.g., "Claude Code"). *)
  val name : string

  (** Model identifiers this backend declares as selectable. The list is
      advisory: an empty list means "let the adapter pick its default", and
      callers should treat unrecognised values as opaque pass-through strings
      forwarded to the CLI. *)
  val models : string list

  (** Optional dynamic enumeration probe.

      When [Some probe], {!Cabal.Adapter_loader.register_all} invokes
      [probe ~sw ~env] once at startup and, if the result is
      [Ok non_empty_list], uses that list as the live model set for the
      backend.  Any [Error _], an [Ok []], or an exception falls back to the
      static {!models} list.

      The probe must be safe: short timeout, no network beyond the CLI's own
      local handshake, no authentication requirement.  If the upstream CLI is
      absent from PATH the probe should return [Error _] cleanly rather than
      raising.  Backends without a stable native enumeration command leave
      this [None]; the static {!models} list remains the load-bearing
      surface. *)
  val models_probe :
    (sw:Eio.Switch.t ->
    env:Eio_unix.Stdenv.base ->
    (string list, string) result)
    option

  (** [available ~sw ~env] checks if this backend is available (installed,
      configured, etc.). This should be a quick check, not a full invocation. *)
  val available : sw:Eio.Switch.t -> env:Eio_unix.Stdenv.base -> bool

  (** Whether this backend supports resuming a prior CLI session. *)
  val supports_session_resume : bool

  (** Whether this backend natively accepts a JSON Schema on invocation and
      enforces it at the CLI level (Story #625).

      When [true], [Json_schema_enforcer.run_task] passes [task_spec.json_schema]
      through to the backend's CLI mechanism rather than running the
      validate-and-retry loop.  The backend's [run_task] is responsible for
      translating [spec.json_schema] into the appropriate CLI flag.

      Callers using the native path are responsible for matching the JSON Schema
      draft expected by the backend's CLI (see the backend's registry evidence
      record for the expected draft). *)
  val native_json_schema_output : bool

  (** Whether a task result represents a backend-specific resume failure. *)
  val is_resume_failure : task_result -> bool

  (** [check_project_config ~sw ~env ~project_dir ~setup_result] validates the
      project-owned configuration just generated for this backend.

      Checks must be local/static or use a backend-native non-network command;
      they must not perform model calls.  Backends without a native/static check
      return [Config_check_unsupported reason] with a non-empty reason. *)
  val check_project_config :
    sw:Eio.Switch.t ->
    env:Eio_unix.Stdenv.base ->
    project_dir:string ->
    setup_result:Backend_config_writer.setup_result ->
    config_check_result

  (** [run_task ~sw ~env ?on_raw_line spec] executes a task using this backend.

      The backend should:
      1. Spawn the agentic client with the given task spec
      2. Wait for completion (or timeout)
      3. Collect output (files changed, structured report if available)
      4. Return a [task_result] with all collected information

      @param sw Eio switch for resource management
      @param env Eio environment for process spawning and I/O
      @param on_raw_line optional per-line callback for raw event capture
      @param spec The task specification to execute
      @return The result of the task execution *)
  val run_task :
    sw:Eio.Switch.t ->
    env:Eio_unix.Stdenv.base ->
    ?on_raw_line:(string -> unit) ->
    task_spec ->
    task_result
end

(** {1 First-Class Module Wrapper} *)

(** A backend packed as a first-class module for storage in the registry. *)
type t = (module S)

(** [id backend] returns the unique identifier of the backend.

    {pre}
    (none)

    {post}
    Returns the same string as [S.id] of the underlying module.

    {violators}
    (none)

    {violates}
    (none)
*)
val id : t -> string

(** [name backend] returns the human-readable name of the backend.

    {pre}
    (none)

    {post}
    Returns the same string as [S.name] of the underlying module.

    {violators}
    (none)

    {violates}
    (none)
*)
val name : t -> string

(** [models backend] returns the model list declared by [backend], or [] when
    unset.

    {pre}
    (none)

    {post}
    Returns the same list as [S.models] of the underlying module.  An empty
    list means the backend has not declared a model set and the caller should
    let the adapter's default model selection apply.

    {violators}
    (none)

    {violates}
    (none)
*)
val models : t -> string list

(** [models_probe backend] returns the optional dynamic enumeration probe
    declared by [backend].

    {pre}
    (none)

    {post}
    Returns [Some probe] when the backend defines a runtime model probe, or
    [None] when only the static {!models} list applies.

    {violators}
    (none)

    {violates}
    (none)
*)
val models_probe :
  t ->
  (sw:Eio.Switch.t -> env:Eio_unix.Stdenv.base -> (string list, string) result)
  option

(** [available ~sw ~env backend] checks if the backend is available.

    {pre}
    [sw] must be an open switch. The check should be fast and non-destructive.

    {post}
    Returns [true] if the backend's toolchain is installed and reachable,
    [false] otherwise. Never raises.

    {violators}
    (none)

    {violates}
    (none)
*)
val available : sw:Eio.Switch.t -> env:Eio_unix.Stdenv.base -> t -> bool

(** [supports_session_resume backend] returns [true] when [backend] supports
    resuming a prior CLI session via [task_spec.resume_session_id].

    {pre}
    (none)

    {post}
    Returns the backend-defined session resume capability flag.

    {violators}
    (none)

    {violates}
    (none)
*)
val supports_session_resume : t -> bool

(** [native_json_schema_output backend] returns [true] when [backend] accepts
    a JSON Schema natively at invocation time (Story #625).

    {pre}
    (none)

    {post}
    Returns the backend-defined native JSON schema output capability flag.

    {violators}
    (none)

    {violates}
    (none)
*)
val native_json_schema_output : t -> bool

(** [is_resume_failure backend result] returns [true] when [result] matches the
    backend-specific shape of a failed resume attempt.

    {pre}
    (none)

    {post}
    Returns the backend-defined resume-failure classification for [result].

    {violators}
    (none)

    {violates}
    (none)
*)
val is_resume_failure : t -> task_result -> bool

(** [check_project_config ~sw ~env ~project_dir ~setup_result backend]
    validates Épure-generated project configuration for [backend].

    {pre}
    [project_dir] must be the project root used for [setup_result].  The check
    must not require network/model calls.

    {post}
    Returns [Config_valid], [Config_invalid msg], or
    [Config_check_unsupported reason].  Unsupported reasons are non-empty when
    backend implementations follow the contract.

    {violators}
    (none)

    {violates}
    (none) *)
val check_project_config :
  sw:Eio.Switch.t ->
  env:Eio_unix.Stdenv.base ->
  project_dir:string ->
  setup_result:Backend_config_writer.setup_result ->
  t ->
  config_check_result

(** [run_task ~sw ~env backend spec] executes a task using the backend.

    This is a low-level compatibility API. Direct use bypasses CBL-03 runtime
    registry/descriptor consistency and central task preflight; hosts wanting
    those guarantees should call [Runtime_dispatch.run_task].

    {pre}
    [backend] must be available (i.e. [available ~sw ~env backend = true]).
    [sw] must be an open switch with sufficient lifetime for the task.

    {post}
    Returns a [task_result] describing the outcome of the task execution,
    including files changed and any structured report produced by the backend.

    {violators}
    (none)

    {violates}
    (none)
*)
val run_task :
  sw:Eio.Switch.t ->
  env:Eio_unix.Stdenv.base ->
  ?on_raw_line:(string -> unit) ->
  t ->
  task_spec ->
  task_result

(** [run_task_with_ctxt ~sw ~env backend request] executes [request.spec] and
    returns [request.ctxt] in the response without inspecting it.

    {pre}
    [backend] must be available, as for {!run_task}. [request.ctxt] may be any
    caller-owned OCaml value; backends must not depend on its representation.

    {post}
    Returns a [task_response] whose [result] is the backend task result and
    whose [ctxt] is exactly the request context passed through unchanged.

    {violators}
    (none)

    {violates}
    (none) *)
val run_task_with_ctxt :
  sw:Eio.Switch.t ->
  env:Eio_unix.Stdenv.base ->
  ?on_raw_line:(string -> unit) ->
  t ->
  'ctxt Backend_types.task_request ->
  'ctxt Backend_types.task_response
