(******************************************************************************)
(*                                                                            *)
(* Copyright (c) 2026 Epure Team                                              *)
(* All rights reserved.                                                       *)
(*                                                                            *)
(******************************************************************************)

type ownership = Epure_owned | Backend_project

type artifact = {
  backend_id : string;
  ownership : ownership;
  managed_namespace : Backend_types.managed_namespace;
  project_relative_path : string;
  content : string;
}

type write_result =
  | Written of string
  | Already_current
  | Refused_hash_mismatch of string
  | Backed_up_and_written of {path : string; backup_path : string}
  | Skipped_user_content of string
  | Unsafe_project_path of string
  | Invalid_managed_namespace of string

type artifact_write_outcome = {
  artifact : artifact;
  project_path : string;
  result : write_result;
}

type setup_result = {
  project_config_path : string option;
  write_outcome : write_result option;
  write_outcomes : artifact_write_outcome list;
}

let default_namespace = Backend_types.default_managed_namespace

let attribution_text_for namespace =
  Printf.sprintf
    "Generated by %s \xe2\x80\x94 do not edit manually"
    namespace.Backend_types.display_name

let attribution_text = attribution_text_for default_namespace

let managed_marker_for (namespace : Backend_types.managed_namespace) =
  namespace.id ^ "-managed"

let managed_marker = managed_marker_for default_namespace

let hash_marker_for (namespace : Backend_types.managed_namespace) =
  namespace.id ^ "-hash"

let sidecar_suffix (namespace : Backend_types.managed_namespace) =
  "." ^ namespace.id ^ "-meta.json"

let temp_suffix (namespace : Backend_types.managed_namespace) =
  "." ^ namespace.id ^ "-tmp"

let backup_suffix (namespace : Backend_types.managed_namespace) =
  "." ^ namespace.id ^ "-backup"

type comment_style = Slash | Hash | Html

let contains_substr s needle =
  let len = String.length s and nlen = String.length needle in
  let rec loop i =
    i + nlen <= len && (String.sub s i nlen = needle || loop (i + 1))
  in
  nlen = 0 || loop 0

let md5_hex s = Digest.to_hex (Digest.string s)

(* Hardcoded legacy namespace used when migrating files written under the
   pre-rename default (id = "epure").  This keeps existing on-disk artifacts
   recognised as managed even after the default was switched to "cabal". *)
let legacy_namespace : Backend_types.managed_namespace =
  {id = "epure"; display_name = "Epure"; config_dir = ".epure/backend-config"}

let marker_candidates namespace marker_for =
  let current = marker_for namespace in
  let dedup xs =
    List.fold_left
      (fun acc x -> if List.mem x acc then acc else acc @ [x])
      []
      xs
  in
  dedup [current; marker_for default_namespace; marker_for legacy_namespace]

let is_managed_content ?(managed_namespace = default_namespace) content =
  List.exists
    (contains_substr content)
    (marker_candidates managed_namespace managed_marker_for)

let extract_hash_with_marker needle content =
  let len = String.length content in
  let nlen = String.length needle in
  let is_hex c =
    (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')
  in
  let rec find i =
    if i + nlen > len then None
    else if String.sub content i nlen = needle then (
      let j = ref (i + nlen) in
      while !j < len && not (is_hex content.[!j]) do
        incr j
      done ;
      if !j >= len then None
      else
        let start = !j in
        while !j < len && is_hex content.[!j] do
          incr j
        done ;
        let h = String.sub content start (!j - start) in
        if String.length h = 32 then Some (String.lowercase_ascii h)
        else find (i + 1))
    else find (i + 1)
  in
  find 0

let extract_hash ?(managed_namespace = default_namespace) content =
  let rec first = function
    | [] -> None
    | marker :: rest -> (
        match extract_hash_with_marker marker content with
        | Some _ as found -> found
        | None -> first rest)
  in
  first (marker_candidates managed_namespace hash_marker_for)

let legacy_metadata_keys =
  ["_epure_attribution"; "_epure-managed"; "_epure-hash"]

let is_legacy_metadata_field name = List.mem name legacy_metadata_keys

let is_epure_header_line ?(managed_namespace = default_namespace) line =
  let trimmed = String.trim line in
  let markers = marker_candidates managed_namespace managed_marker_for in
  let hash_markers = marker_candidates managed_namespace hash_marker_for in
  let attributions =
    [
      attribution_text;
      attribution_text_for managed_namespace;
      attribution_text_for legacy_namespace;
    ]
  in
  let is_comment_header =
    (String.starts_with ~prefix:"#" trimmed
    || String.starts_with ~prefix:"//" trimmed
    || String.starts_with ~prefix:"<!--" trimmed)
    && List.exists
         (contains_substr trimmed)
         (attributions @ markers @ hash_markers)
  in
  let is_exact_legacy_json_field =
    List.exists
      (fun key -> contains_substr trimmed (Printf.sprintf "\"%s\"" key))
      legacy_metadata_keys
  in
  is_comment_header || is_exact_legacy_json_field

let strip_epure_header_lines ?(managed_namespace = default_namespace) content =
  content |> String.split_on_char '\n'
  |> List.filter (fun l -> not (is_epure_header_line ~managed_namespace l))
  |> String.concat "\n"

(* JSON-with-comments cleanup helpers live in Backend_config_cleanup. *)

let body_for_hash ?(managed_namespace = default_namespace) content =
  let body =
    content
    |> strip_epure_header_lines ~managed_namespace
    |> Backend_config_cleanup.strip_managed_mcp_block
    |> String.split_on_char '\n'
    |> List.filter (fun l -> String.trim l <> "")
    |> String.concat "\n"
  in
  let compact =
    body |> String.split_on_char '\n' |> List.map String.trim
    |> String.concat ""
  in
  if compact = "{}" then "{}" else body

let is_json_object_content ?(managed_namespace = default_namespace) content =
  match String.trim (strip_epure_header_lines ~managed_namespace content) with
  | s when String.length s > 0 -> s.[0] = '{'
  | _ -> false

let managed_body_hash ?(managed_namespace = default_namespace) ~backend_id:_
    content =
  md5_hex (body_for_hash ~managed_namespace content)

let comment_line style text =
  match style with
  | Slash -> Printf.sprintf "// %s\n" text
  | Hash -> Printf.sprintf "# %s\n" text
  | Html -> Printf.sprintf "<!-- %s -->\n" text

let with_epure_header ?(managed_namespace = default_namespace) style body =
  comment_line style (attribution_text_for managed_namespace)
  ^ comment_line style (managed_marker_for managed_namespace)
  ^ body

let with_managed_header ?(managed_namespace = default_namespace) style
    ~backend_id body =
  let hash = managed_body_hash ~managed_namespace ~backend_id body in
  comment_line style (attribution_text_for managed_namespace)
  ^ comment_line style (managed_marker_for managed_namespace)
  ^ comment_line style (hash_marker_for managed_namespace ^ ": " ^ hash)
  ^ body

let has_legacy_metadata_keys content =
  List.exists
    (fun key -> contains_substr content (Printf.sprintf "\"%s\"" key))
    legacy_metadata_keys

let migrate_legacy_managed_json_content content =
  try
    match Yojson.Safe.from_string content with
    | `Assoc fields ->
        (* Always rewrite under the current default attribution so migrated
           files don't keep the legacy "Generated by Epure" line. *)
        let attribution = attribution_text in
        let kept_fields =
          List.filter
            (fun (name, _) -> not (is_legacy_metadata_field name))
            fields
        in
        let body =
          match kept_fields with
          | [] -> "{\n}"
          | _ -> Yojson.Safe.pretty_to_string (`Assoc kept_fields)
        in
        let body = body ^ "\n" in
        let hash = managed_body_hash ~backend_id:"legacy-jsonc" body in
        Some
          (comment_line Slash attribution
          ^ comment_line Slash managed_marker
          ^ comment_line Slash (hash_marker_for default_namespace ^ ": " ^ hash)
          ^ body)
    | _ -> None
  with _ -> None

exception Unsafe_project_path_error

type project_file_read = Missing | File of string | Unsafe

let unsafe_project_path () = raise Unsafe_project_path_error

let relative_components path =
  if
    path = "" || not (Filename.is_relative path)
    || String.exists (fun character -> character = '\000') path
  then unsafe_project_path ()
  else
    let components = String.split_on_char '/' path in
    if
      List.exists
        (fun component -> component = "" || component = "." || component = "..")
        components
    then unsafe_project_path ()
    else components

let opened_project_root project_dir =
  try
    let root = Unix.realpath project_dir in
    if (Unix.stat root).Unix.st_kind <> Unix.S_DIR then unsafe_project_path () ;
    root
  with
  | Unsafe_project_path_error -> raise Unsafe_project_path_error
  | _ -> unsafe_project_path ()

let rec ensure_safe_directories ~create current = function
  | [] -> true
  | component :: rest ->
      let next = Filename.concat current component in
      let exists =
        try
          match (Unix.lstat next).Unix.st_kind with
          | Unix.S_DIR -> true
          | Unix.S_LNK | Unix.S_REG | Unix.S_CHR | Unix.S_BLK | Unix.S_FIFO
          | Unix.S_SOCK ->
              unsafe_project_path ()
        with
        | Unix.Unix_error (Unix.ENOENT, _, _) when create ->
            Unix.mkdir next 0o755 ;
            (match (Unix.lstat next).Unix.st_kind with
            | Unix.S_DIR -> true
            | _ -> unsafe_project_path ())
        | Unix.Unix_error (Unix.ENOENT, _, _) -> false
      in
      exists && ensure_safe_directories ~create next rest

let safe_full_path ~project_root ~create_parent relative_path =
  let components = relative_components relative_path in
  match List.rev components with
  | [] -> unsafe_project_path ()
  | basename :: reversed_parent ->
      let parent = List.rev reversed_parent in
      if not (ensure_safe_directories ~create:create_parent project_root parent)
      then raise Not_found ;
      (Filename.concat
         (List.fold_left Filename.concat project_root parent)
         basename,
       basename)

let prevalidate_publication_path ~project_root ~create_parent relative_path =
  let path, _ = safe_full_path ~project_root ~create_parent relative_path in
  (try
     if (Unix.lstat path).Unix.st_kind <> Unix.S_REG then unsafe_project_path ()
   with Unix.Unix_error (Unix.ENOENT, _, _) -> ()) ;
  path

let read_existing_regular path =
  let before = Unix.lstat path in
  if before.Unix.st_kind = Unix.S_LNK then unsafe_project_path () ;
  if before.st_kind <> Unix.S_REG then unsafe_project_path () ;
  let descriptor =
    Unix.openfile path [Unix.O_RDONLY; Unix.O_CLOEXEC; Unix.O_NONBLOCK] 0
  in
  Fun.protect
    ~finally:(fun () -> Unix.close descriptor)
    (fun () ->
      let opened = Unix.fstat descriptor in
      if
        opened.st_kind <> Unix.S_REG || opened.st_dev <> before.st_dev
        || opened.st_ino <> before.st_ino
      then unsafe_project_path () ;
      let length = opened.st_size in
      let buffer = Bytes.create length in
      let rec read offset =
        if offset < length then
          let count = Unix.read descriptor buffer offset (length - offset) in
          if count = 0 then unsafe_project_path () else read (offset + count)
      in
      read 0 ;
      Bytes.to_string buffer)

let read_file_opt ~project_root ~relative_path =
  try
    let path, _ = safe_full_path ~project_root ~create_parent:false relative_path in
    Some (read_existing_regular path)
  with
  | Not_found | Unix.Unix_error (Unix.ENOENT, _, _) -> None

let inspect_project_file ~project_dir ~relative_path =
  try
    let project_root = opened_project_root project_dir in
    match read_file_opt ~project_root ~relative_path with
    | None -> Missing
    | Some content -> File content
  with _ -> Unsafe

type sidecar_metadata = {
  generated_by : string;
  backend_id : string;
  target : string;
  content_hash : string;
}
[@@deriving yojson]

let sidecar_path ~managed_namespace full_path =
  full_path ^ sidecar_suffix managed_namespace

let legacy_sidecar_path full_path = full_path ^ sidecar_suffix default_namespace

let sidecar_metadata_for (artifact : artifact) =
  {
    generated_by = artifact.managed_namespace.id;
    backend_id = artifact.backend_id;
    target = artifact.project_relative_path;
    content_hash = md5_hex artifact.content;
  }

let sidecar_content artifact =
  sidecar_metadata_to_yojson (sidecar_metadata_for artifact)
  |> Yojson.Safe.pretty_to_string
  |> fun s -> s ^ "\n"

let parse_sidecar_metadata content =
  try
    match sidecar_metadata_of_yojson (Yojson.Safe.from_string content) with
    | Ok meta -> Some meta
    | Error _ -> None
  with _ -> None

let read_sidecar_metadata ~project_root ~full_path (artifact : artifact) =
  let paths =
    let current =
      sidecar_path ~managed_namespace:artifact.managed_namespace full_path
    in
    let legacy = legacy_sidecar_path full_path in
    if current = legacy then [current] else [current; legacy]
  in
  let rec read = function
    | [] -> None
    | path :: rest -> (
        let relative_path =
          String.sub path (String.length project_root + 1)
            (String.length path - String.length project_root - 1)
        in
        match read_file_opt ~project_root ~relative_path with
        | None -> read rest
        | Some content -> Some content)
  in
  match read paths with
  | None -> None
  | Some content -> (
      match parse_sidecar_metadata content with
      | Some meta
        when (meta.generated_by = artifact.managed_namespace.id
             || meta.generated_by = default_namespace.id)
             && meta.backend_id = artifact.backend_id
             && meta.target = artifact.project_relative_path ->
          Some meta
      | _ -> None)

let uses_sidecar_metadata artifact =
  artifact.ownership = Backend_project
  && not
       (is_managed_content
          ~managed_namespace:artifact.managed_namespace
          artifact.content)

type owned_temp = {path : string; device : int; inode : int}

let temp_create_attempt_limit = 32

let valid_temp_nonce nonce =
  let length = String.length nonce in
  length > 0 && length <= 128
  && String.for_all
       (function
         | 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | '_' -> true
         | _ -> false)
       nonce

let default_nonce_generator () =
  let state = Random.State.make_self_init () in
  fun attempt ->
    Printf.sprintf "%08x%08x%08x-%02x" (Random.State.bits state)
      (Random.State.bits state) (Random.State.bits state) attempt

let rec fstat_no_intr descriptor =
  try Unix.fstat descriptor
  with Unix.Unix_error (Unix.EINTR, _, _) -> fstat_no_intr descriptor

let create_unique_temp ?nonce_for_attempt ~managed_namespace path =
  let nonce_for_attempt =
    Option.value ~default:(default_nonce_generator ()) nonce_for_attempt
  in
  let rec create attempt =
    if attempt >= temp_create_attempt_limit then
      raise (Unix.Unix_error (Unix.EEXIST, "open", path)) ;
    let nonce = nonce_for_attempt attempt in
    if not (valid_temp_nonce nonce) then invalid_arg "invalid temporary nonce" ;
    let temp_path = path ^ temp_suffix managed_namespace ^ "-" ^ nonce in
    match
      Unix.openfile temp_path
        [Unix.O_WRONLY; Unix.O_CREAT; Unix.O_EXCL; Unix.O_CLOEXEC]
        0o600
    with
    | descriptor ->
        let opened =
          try fstat_no_intr descriptor
          with error ->
            Unix.close descriptor ;
            raise error
        in
        let created =
          {path = temp_path; device = opened.st_dev; inode = opened.st_ino}
        in
        (try
           Unix.fchmod descriptor 0o600 ;
           (descriptor, created)
         with error ->
           Unix.close descriptor ;
           (try
              let current = Unix.lstat created.path in
              if
                current.st_kind = Unix.S_REG
                && current.st_dev = created.device
                && current.st_ino = created.inode
              then Unix.unlink created.path
            with _ -> ()) ;
           raise error)
    | exception Unix.Unix_error (Unix.EEXIST, _, _) -> create (attempt + 1)
  in
  create 0

let unlink_if_owned owned =
  try
    let current = Unix.lstat owned.path in
    if
      current.st_kind = Unix.S_REG && current.st_dev = owned.device
      && current.st_ino = owned.inode
    then Unix.unlink owned.path
  with Unix.Unix_error (Unix.ENOENT, _, _) -> ()

let temp_is_owned owned =
  try
    let current = Unix.lstat owned.path in
    current.st_kind = Unix.S_REG && current.st_dev = owned.device
    && current.st_ino = owned.inode
  with Unix.Unix_error (Unix.ENOENT, _, _) -> false

let atomic_write_file_with_hooks ?(managed_namespace = default_namespace)
    ?nonce_for_attempt ?after_write ~project_root ~relative_path content =
  let path =
    prevalidate_publication_path ~project_root ~create_parent:true relative_path
  in
  let existing_perm =
    try Some ((Unix.lstat path).Unix.st_perm land 0o777)
    with Unix.Unix_error (Unix.ENOENT, _, _) -> None
  in
  let owned = ref None in
  Fun.protect
    ~finally:(fun () -> Option.iter unlink_if_owned !owned)
    (fun () ->
      let descriptor, created =
        create_unique_temp ?nonce_for_attempt ~managed_namespace path
      in
      owned := Some created ;
      Fun.protect
        ~finally:(fun () -> Unix.close descriptor)
        (fun () ->
          let rec write offset =
            if offset < String.length content then
              let count =
                Unix.write_substring descriptor content offset
                  (String.length content - offset)
              in
              if count = 0 then raise End_of_file else write (offset + count)
          in
          write 0 ;
          Unix.fsync descriptor ;
          Option.iter (fun hook -> hook created.path) after_write ;
          Option.iter (Unix.fchmod descriptor) existing_perm) ;
      ignore
        (prevalidate_publication_path ~project_root ~create_parent:false
           relative_path) ;
      if not (temp_is_owned created) then
        raise (Unix.Unix_error (Unix.EAGAIN, "rename", created.path)) ;
      Unix.rename created.path path ;
      owned := None)

let atomic_write_file ?managed_namespace ~project_root ~relative_path content =
  atomic_write_file_with_hooks ?managed_namespace ~project_root ~relative_path
    content

let relative_to_root ~project_root path =
  let prefix = project_root ^ Filename.dir_sep in
  if String.starts_with ~prefix path then
    String.sub path (String.length prefix) (String.length path - String.length prefix)
  else unsafe_project_path ()

let copy_file ?(managed_namespace = default_namespace) ~project_root src dst =
  match
    read_file_opt ~project_root
      ~relative_path:(relative_to_root ~project_root src)
  with
  | None -> Error (Printf.sprintf "cannot read '%s' for backup" src)
  | Some content -> (
      try
        atomic_write_file ~managed_namespace ~project_root
          ~relative_path:(relative_to_root ~project_root dst)
          content ;
        Ok ()
      with e -> Error (Printexc.to_string e))

let write_sidecar_metadata ~project_root full_path artifact =
  atomic_write_file
    ~managed_namespace:artifact.managed_namespace
    ~project_root
    ~relative_path:
      (relative_to_root ~project_root
         (sidecar_path ~managed_namespace:artifact.managed_namespace full_path))
    (sidecar_content artifact)

let prevalidate_sidecar_artifact_paths ~project_root ~force
    (artifact : artifact) =
  let target = artifact.project_relative_path in
  let current_sidecar = target ^ sidecar_suffix artifact.managed_namespace in
  let legacy_sidecar = target ^ sidecar_suffix default_namespace in
  let paths =
    if current_sidecar = legacy_sidecar then [target; current_sidecar]
    else [target; current_sidecar; legacy_sidecar]
  in
  let paths =
    if force then
      (target ^ backup_suffix artifact.managed_namespace) :: paths
    else paths
  in
  List.iter
    (fun relative_path ->
      ignore
        (prevalidate_publication_path ~project_root ~create_parent:true
           relative_path))
    paths

let write_sidecar_artifact ~project_root ~force artifact =
  prevalidate_sidecar_artifact_paths ~project_root ~force artifact ;
  let full_path = Filename.concat project_root artifact.project_relative_path in
  match read_file_opt ~project_root ~relative_path:artifact.project_relative_path with
  | None ->
      atomic_write_file
        ~managed_namespace:artifact.managed_namespace
        ~project_root ~relative_path:artifact.project_relative_path
        artifact.content ;
      write_sidecar_metadata ~project_root full_path artifact ;
      Written full_path
  | Some existing -> (
      match read_sidecar_metadata ~project_root ~full_path artifact with
      | None -> Skipped_user_content full_path
      | Some meta ->
          let h_current = md5_hex existing in
          if h_current = meta.content_hash then
            if existing = artifact.content then Already_current
            else begin
              atomic_write_file
                ~managed_namespace:artifact.managed_namespace
                ~project_root ~relative_path:artifact.project_relative_path
                artifact.content ;
              write_sidecar_metadata ~project_root full_path artifact ;
              Written full_path
            end
          else if force then (
            let backup_path =
              full_path ^ backup_suffix artifact.managed_namespace
            in
            match
              copy_file
                ~managed_namespace:artifact.managed_namespace
                ~project_root
                full_path
                backup_path
            with
            | Error msg ->
                Refused_hash_mismatch
                  (Printf.sprintf
                     "Cannot backup '%s': %s. Fix the backup location or run \
                      without --force."
                     full_path
                     msg)
            | Ok () ->
                atomic_write_file
                  ~managed_namespace:artifact.managed_namespace
                  ~project_root ~relative_path:artifact.project_relative_path
                  artifact.content ;
                write_sidecar_metadata ~project_root full_path artifact ;
                Backed_up_and_written {path = full_path; backup_path})
          else
            Refused_hash_mismatch
              (Printf.sprintf
                 "File '%s' has been modified (sidecar hash mismatch). Run \
                  with --force to backup and overwrite."
                 full_path))

let write_artifact_unchecked ~project_root ~force artifact =
  match Backend_types.validate_managed_namespace artifact.managed_namespace with
  | Error msg -> Invalid_managed_namespace msg
  | Ok () -> (
       let full_path = Filename.concat project_root artifact.project_relative_path in
       if uses_sidecar_metadata artifact then
         write_sidecar_artifact ~project_root ~force artifact
       else
         match artifact.ownership with
         | Epure_owned ->
             let existing =
               read_file_opt ~project_root
                 ~relative_path:artifact.project_relative_path
             in
            if existing = Some artifact.content then Already_current
            else begin
               atomic_write_file
                 ~managed_namespace:artifact.managed_namespace
                 ~project_root ~relative_path:artifact.project_relative_path
                 artifact.content ;
              Written full_path
            end
         | Backend_project -> (
             match
               read_file_opt ~project_root
                 ~relative_path:artifact.project_relative_path
             with
            | None ->
                 atomic_write_file
                   ~managed_namespace:artifact.managed_namespace
                   ~project_root ~relative_path:artifact.project_relative_path
                   artifact.content ;
                Written full_path
            | Some existing -> (
                if
                  not
                    (is_managed_content
                       ~managed_namespace:artifact.managed_namespace
                       existing)
                then Skipped_user_content full_path
                else
                  let h_current =
                    managed_body_hash
                      ~managed_namespace:artifact.managed_namespace
                      ~backend_id:artifact.backend_id
                      existing
                  in
                  match
                    extract_hash
                      ~managed_namespace:artifact.managed_namespace
                      existing
                  with
                  | None ->
                      if existing = artifact.content then Already_current
                      else begin
                         atomic_write_file
                           ~managed_namespace:artifact.managed_namespace
                           ~project_root
                           ~relative_path:artifact.project_relative_path
                           artifact.content ;
                        Written full_path
                      end
                  | Some h_file ->
                      if h_current = h_file then
                        if has_legacy_metadata_keys existing then
                          match
                            migrate_legacy_managed_json_content existing
                          with
                          | Some migrated ->
                               atomic_write_file
                                 ~managed_namespace:artifact.managed_namespace
                                 ~project_root
                                 ~relative_path:artifact.project_relative_path
                                 migrated ;
                              Written full_path
                          | None ->
                              Refused_hash_mismatch
                                (Printf.sprintf
                                   "File '%s' uses legacy Épure metadata, but \
                                    it could not be migrated safely. Leaving \
                                    it unchanged."
                                   full_path)
                        else if
                          is_json_object_content
                            ~managed_namespace:artifact.managed_namespace
                            existing
                          && is_json_object_content
                               ~managed_namespace:artifact.managed_namespace
                               artifact.content
                        then Already_current
                        else if
                          body_for_hash
                            ~managed_namespace:artifact.managed_namespace
                            existing
                          = body_for_hash
                              ~managed_namespace:artifact.managed_namespace
                              artifact.content
                        then Already_current
                        else if
                          extract_hash
                            ~managed_namespace:artifact.managed_namespace
                            artifact.content
                          = Some h_file
                        then Already_current
                        else begin
                           atomic_write_file
                             ~managed_namespace:artifact.managed_namespace
                             ~project_root
                             ~relative_path:artifact.project_relative_path
                             artifact.content ;
                          Written full_path
                        end
                      else if force then (
                        let backup_relative_path =
                          artifact.project_relative_path
                          ^ backup_suffix artifact.managed_namespace
                        in
                        let backup_path =
                          full_path ^ backup_suffix artifact.managed_namespace
                        in
                        ignore
                          (prevalidate_publication_path ~project_root
                             ~create_parent:true backup_relative_path) ;
                        match
                           copy_file
                             ~managed_namespace:artifact.managed_namespace
                             ~project_root
                             full_path
                             backup_path
                        with
                        | Error msg ->
                            Refused_hash_mismatch
                              (Printf.sprintf
                                 "Cannot backup '%s': %s. Fix the backup \
                                  location or run without --force."
                                 full_path
                                 msg)
                        | Ok () ->
                             atomic_write_file
                               ~managed_namespace:artifact.managed_namespace
                               ~project_root
                               ~relative_path:artifact.project_relative_path
                               artifact.content ;
                            Backed_up_and_written
                              {path = full_path; backup_path})
                      else
                        Refused_hash_mismatch
                          (Printf.sprintf
                             "File '%s' has been modified (hash mismatch). Run \
                              with --force to backup and overwrite."
                             full_path))))

let write_artifact ~project_dir ~force artifact =
  try
    let project_root = opened_project_root project_dir in
    ignore (relative_components artifact.project_relative_path) ;
    write_artifact_unchecked ~project_root ~force artifact
  with
  | Unsafe_project_path_error | Not_found
  | Unix.Unix_error ((Unix.ELOOP | Unix.ENOTDIR | Unix.EACCES), _, _) ->
      Unsafe_project_path "project configuration path is unsafe"

let setup_artifacts ~project_dir ~force = function
  | [] ->
      {project_config_path = None; write_outcome = None; write_outcomes = []}
  | primary :: _ as artifacts ->
      let write_one artifact =
        match
          Backend_types.validate_managed_namespace artifact.managed_namespace
        with
        | Error msg ->
            {
              artifact;
              project_path = "";
              result = Invalid_managed_namespace msg;
            }
        | Ok () ->
            let result = write_artifact ~project_dir ~force artifact in
            {
              artifact;
              project_path =
                Filename.concat project_dir artifact.project_relative_path;
              result;
            }
      in
      let write_outcomes = List.map write_one artifacts in
      let primary_result =
        match write_outcomes with
        | {result; _} :: _ -> result
        | [] -> assert false
      in
      let project_config_path =
        match primary.ownership with
        | Backend_project -> None
        | Epure_owned -> (
            match primary_result with
            | Written path | Backed_up_and_written {path; _} -> Some path
            | Already_current ->
                Some (Filename.concat project_dir primary.project_relative_path)
            | Refused_hash_mismatch _ | Skipped_user_content _
            | Unsafe_project_path _
            | Invalid_managed_namespace _ ->
                None)
      in
      {project_config_path; write_outcome = Some primary_result; write_outcomes}

let write_result_was_applied = function
  | Written _ | Already_current | Backed_up_and_written _ -> true
  | Refused_hash_mismatch _ | Skipped_user_content _ | Unsafe_project_path _
  | Invalid_managed_namespace _ ->
      false

let config_was_applied = function
  | Some result -> write_result_was_applied result
  | _ -> false

let precedence_warning_for ~backend_id ~write_outcome =
  match Backend_registry.find backend_id with
  | None -> None
  | Some desc -> (
      let open Backend_registry in
      let applied = config_was_applied write_outcome in
      match desc.capabilities.precedence_confidence with
      | High -> None
      | Medium ->
          if applied then
            Some
              (Printf.sprintf
                 "Warning [%s]: project config has been written but \
                  user-global settings may partially override it in some \
                  scenarios. Behavior may differ between machines. Ensure no \
                  conflicting global config exists."
                 desc.display_name)
          else
            Some
              (Printf.sprintf
                 "Warning [%s]: project config could not be applied (file \
                  exists with user-authored content or was refused). \
                  Invocation will rely on user-global settings only. Behavior \
                  may differ between machines."
                 desc.display_name)
      | Low -> (
          match desc.capabilities.project_config_surface with
          | Config_none ->
              Some
                (Printf.sprintf
                   "Warning [%s]: no project config surface available. Épure \
                    cannot inject project-level configuration; invocations \
                    rely entirely on user-global settings. Behavior will vary \
                    between machines."
                   desc.display_name)
          | _ -> (
              if applied then
                Some
                  (Printf.sprintf
                     "Warning [%s]: limited project config precedence \
                      controls. The project config file has been written but \
                      user-global settings may silently override project \
                      settings. Épure configures the strongest supported \
                      behavior for this backend. Behavior may differ between \
                      machines."
                     desc.display_name)
              else
                match write_outcome with
                | None ->
                    Some
                      (Printf.sprintf
                         "Warning [%s]: no project config write was attempted \
                          for this invocation. Invocation will rely entirely \
                          on user-global settings. Behavior may differ between \
                          machines."
                         desc.display_name)
                | Some (Skipped_user_content _) ->
                    Some
                      (Printf.sprintf
                         "Warning [%s]: limited project config precedence \
                          controls. The project config file could not be \
                          applied (user-authored content at the expected \
                          path). Invocation will rely entirely on user-global \
                          settings."
                         desc.display_name)
                | Some (Refused_hash_mismatch _) ->
                    Some
                      (Printf.sprintf
                         "Warning [%s]: limited project config precedence \
                          controls. The project config file was not applied \
                          (hash mismatch — run with --force-config to backup \
                          and overwrite). Invocation will rely entirely on \
                          user-global settings."
                         desc.display_name)
                | Some (Invalid_managed_namespace msg) ->
                    Some
                      (Printf.sprintf
                         "Warning [%s]: project config was not applied because \
                          the managed namespace is invalid: %s"
                         desc.display_name
                         msg)
                | Some (Unsafe_project_path _) ->
                    Some
                      (Printf.sprintf
                         "Warning [%s]: project config path was unsafe; no file \
                          was written."
                         desc.display_name)
                | _ -> None)))

module Private = struct
  type nonrec project_file_read = project_file_read =
    | Missing
    | File of string
    | Unsafe

  let inspect_project_file = inspect_project_file
  let atomic_write_file_with_hooks = atomic_write_file_with_hooks
end
