(******************************************************************************)
(*                                                                            *)
(* Copyright (c) 2026 Epure Team                                              *)
(* All rights reserved.                                                       *)
(*                                                                            *)
(******************************************************************************)

(** Google Gemini CLI agentic backend.

    This module implements the [AGENTIC_BACKEND.S] interface for the
    Google Gemini CLI tool. It spawns [gemini] in non-interactive mode
    with stream-json NDJSON output and collects results.

    {b Configuration:}
    Gemini CLI is expected to be installed and accessible in the PATH.
    The backend uses [--output-format stream-json -y --skip-trust -p -] for
    non-interactive headless execution with auto-approval and non-interactive
    trusted-folder checks. Stream-json emits one JSON event per stdout line,
    which is captured by the [on_raw_line] hook and redacted by
    [Backend_event_redaction] before NDJSON persistence (Story #484 AC2).

    {b MCP Integration:}
    Gemini supports MCP servers configured in settings JSON. Épure writes
    workspace [.gemini/settings.json] and serializes [task_spec.mcp_servers]
    into its top-level [mcpServers] object.  If MCP servers are requested but
    the settings artifact is user-authored or hash-mismatched, the backend
    returns a clear failure instead of invoking Gemini without MCP. *)

(** @inline *)
include Agentic_backend.S

(** {1 Additional Utilities} *)

(** [project_config_artifacts ~mcp_servers ~lsp_servers] returns the
    Gemini project config artifacts owned by this backend provider.

    {pre}
    (none)

    {post}
    Returns strict JSON [.gemini/settings.json].  [GEMINI.md] is project
    context and is not generated by default.

    {violators}
    (none)

    {violates}
    (none) *)
val project_config_artifacts :
  managed_namespace:Backend_types.managed_namespace ->
  mcp_servers:Backend_types.mcp_server_config list ->
  lsp_servers:Backend_types.lsp_server_config list ->
  Backend_config_writer.artifact list

(** [parse_gemini_json_output json] parses a single Gemini CLI JSON event
    object and extracts the response text and optional cost information.

    {pre}
    (none)

    {post}
    Returns a pair of the extracted response text and optional cost data parsed from the Gemini JSON output.

    {violators}
    (none)

    {violates}
    (none)
*)
val parse_gemini_json_output :
  Yojson.Safe.t -> string * Backend_types.cost option

(** [parse_gemini_stream_json stdout] parses Gemini CLI's stream-json NDJSON
    stdout (one JSON event per line) and returns [(text, cost, session_id)].

    Text is assembled from [response]/[result] fields (complete response) or
    concatenated [text] fields (incremental chunks). Cost is taken from the
    last event with [usageMetadata] or [usage]. Session ID from [session_id].

    Non-JSON lines are silently skipped.

    {pre}
    (none)

    {post}
    Returns a triple: assembled text, optional cost, and optional session_id.
    Never raises. Returns [""] for text and [None] for cost/session_id when
    [stdout] contains no parseable event lines.

    {violators}
    (none)

    {violates}
    (none)
*)
val parse_gemini_stream_json :
  string -> string * Backend_types.cost option * string option

(** [parse_stdout_text stdout] extracts the agent response text from
    Gemini's stream-json NDJSON stdout.  It prefers the last [response] or
    [result] field, falling back to concatenated [text] chunks, and finally
    to the raw [stdout] when nothing could be extracted.

    {pre}
    (none)

    {post}
    Returns the assembled response text, or the raw [stdout] when extraction
    yields the empty string.

    {violators}
    (none)

    {violates}
    (none) *)
val parse_stdout_text : string -> string

(** [build_command ~mcp_config_path spec] constructs the Gemini CLI command and
    stdin content.  Gemini CLI 0.38.2 has no native read-only sandbox;
    [spec.read_only] is acknowledged as documented limitation and the baseline
    command is returned unchanged.  Includes [--skip-trust] so headless
    temporary workspaces do not block on trusted-folder prompts.  Exported for
    testing.

    {pre}
    (none)

    {post}
    Returns [(cmd_list, stdin_content)].  Includes [-m <model>] when
    [spec.model] is set, [--skip-trust] for headless trusted-folder checks, and
    [--resume <session_id>] when [spec.resume_session_id] is set.  Command is
    otherwise identical for [read_only = true] and [read_only = false] (no
    native restriction model).

    {violators}
    (none)

    {violates}
    (none) *)
val build_command :
  mcp_config_path:string option ->
  Backend_types.task_spec ->
  string list * string

(** [supports_session_resume] is [true]: Gemini CLI 0.38.2 supports
    [--resume <session_id>] to continue a prior session.  Mirrors the
    [session_resume = true] field in the backend registry (Story #516). *)
val supports_session_resume : bool
