(******************************************************************************)
(*                                                                            *)
(* Copyright (c) 2026 Epure Team                                              *)
(* All rights reserved.                                                       *)
(*                                                                            *)
(******************************************************************************)

(** Tests for Story #482 — Gemini CLI parity uplift (Gemini CLI 0.38.2).

    Covers:
    - AC1: JSON headless and stream-json support reflected in capabilities
    - AC2: MCP wired as settings-file based (Gemini reads settings.json;
           no per-invocation file injection); no secrets in generated config
    - AC3: Workspace [.gemini/settings.json] config strategy implemented;
           GEMINI.md is project context and not generated by default
    - AC4: Parity targets stable channel only, not preview or nightly *)

open Cabal

let contains_str s needle =
  let len = String.length s and nlen = String.length needle in
  let rec loop i =
    i + nlen <= len && (String.sub s i nlen = needle || loop (i + 1))
  in
  nlen = 0 || loop 0

let with_tmpdir f =
  let dir = Filename.temp_dir "epure_test_482_" "" in
  Fun.protect
    ~finally:(fun () ->
      ignore (Sys.command (Printf.sprintf "rm -rf %s" (Filename.quote dir))))
    (fun () -> f dir)

let rec ensure_parent_dir path =
  let dir = Filename.dirname path in
  if dir = path || dir = "." then ()
  else begin
    ensure_parent_dir dir ;
    if not (Sys.file_exists dir) then Unix.mkdir dir 0o755
  end

let write_file path content =
  ensure_parent_dir path ;
  let oc = open_out path in
  output_string oc content ;
  close_out oc

let read_file path =
  let ic = open_in_bin path in
  let n = in_channel_length ic in
  let buf = Bytes.create n in
  really_input ic buf 0 n ;
  close_in ic ;
  Bytes.to_string buf

let epure_mcp_server () =
  Backend_types.make_mcp_server_config
    ~name:"epure"
    ~command:"epure-mcp-server"
    ~args:["--stdio"]
    ~env:[("EPURE_PROJECT", "/tmp/project")]
    ()

let task_spec_with_mcp dir =
  Backend_types.make_task_spec
    ~prompt:"test"
    ~working_dir:dir
    ~mcp_servers:[epure_mcp_server ()]
    ()

let check_failed_with_mcp_path result path =
  match result.Backend_types.status with
  | Backend_types.Failed msg ->
      Alcotest.(check bool) "failure mentions MCP" true (contains_str msg "MCP") ;
      Alcotest.(check bool)
        "failure mentions settings path"
        true
        (contains_str msg path)
  | _ -> Alcotest.fail "expected Gemini run_task to fail before invocation"

(** {1 AC1 — JSON headless: structured_output = true} *)

let test_gemini_structured_output () =
  let open Backend_registry in
  match find "gemini-cli" with
  | None -> Alcotest.fail "gemini-cli descriptor not found"
  | Some d ->
      Alcotest.(check bool)
        "AC1: gemini-cli structured_output = true"
        true
        d.capabilities.structured_output

(** {1 AC1 — stream-json: streaming_output = true} *)

let test_gemini_streaming_output () =
  let open Backend_registry in
  match find "gemini-cli" with
  | None -> Alcotest.fail "gemini-cli descriptor not found"
  | Some d ->
      Alcotest.(check bool)
        "AC1: gemini-cli streaming_output = true"
        true
        d.capabilities.streaming_output

(** {1 AC2 — MCP support mode is Mcp_user_settings}

    Gemini 0.38.2 reads MCP config from [settings.json] files; workspace
    [.gemini/settings.json] overrides user settings, but there is no CLI flag
    for per-invocation MCP file injection.
    The [mcp_config_path] arg in [build_command] is intentionally unused. *)

let test_gemini_mcp_support_is_user_settings () =
  let open Backend_registry in
  match find "gemini-cli" with
  | None -> Alcotest.fail "gemini-cli descriptor not found"
  | Some d ->
      Alcotest.(check bool)
        "AC2: gemini-cli mcp_support = Mcp_user_settings"
        true
        (d.capabilities.mcp_support = Mcp_user_settings)

(** {1 AC2 — Generated settings contain MCP server map} *)

let test_gemini_config_contains_mcp_reference () =
  match Backend_config_gen.generate ~backend_id:"gemini-cli" with
  | None -> Alcotest.fail "expected artifact for gemini-cli"
  | Some a ->
      let lower = String.lowercase_ascii a.Backend_config_gen.content in
      Alcotest.(check bool)
        "AC2: settings contain mcp reference"
        true
        (contains_str lower "mcp")

let test_gemini_config_points_mcp_to_workspace_settings () =
  match Backend_config_gen.generate ~backend_id:"gemini-cli" with
  | None -> Alcotest.fail "expected artifact for gemini-cli"
  | Some a -> (
      Alcotest.(check string)
        "AC2: generated path is workspace settings"
        ".gemini/settings.json"
        a.Backend_config_gen.project_relative_path ;
      let json = Yojson.Safe.from_string a.Backend_config_gen.content in
      match json with
      | `Assoc fields when List.mem_assoc "mcpServers" fields -> ()
      | _ -> Alcotest.fail "expected top-level mcpServers")

(** {1 AC2 — Generated settings MCP map is empty by default} *)

let test_gemini_config_mcp_is_disabled () =
  match Backend_config_gen.generate ~backend_id:"gemini-cli" with
  | None -> Alcotest.fail "expected artifact for gemini-cli"
  | Some a -> (
      let json = Yojson.Safe.from_string a.Backend_config_gen.content in
      match json with
      | `Assoc fields -> (
          match List.assoc_opt "mcpServers" fields with
          | Some (`Assoc []) -> ()
          | Some other ->
              Alcotest.failf
                "expected empty mcpServers, got %s"
                (Yojson.Safe.to_string other)
          | None -> Alcotest.fail "expected mcpServers")
      | _ -> Alcotest.fail "expected settings JSON object")

(** {1 AC2 — Generated config contains no secrets} *)

let test_gemini_config_no_secrets () =
  match Backend_config_gen.generate ~backend_id:"gemini-cli" with
  | None -> Alcotest.fail "expected artifact for gemini-cli"
  | Some a ->
      let content = String.lowercase_ascii a.Backend_config_gen.content in
      let secret_keywords =
        ["password"; "credential"; "bearer"; "private_key"]
      in
      List.iter
        (fun kw ->
          Alcotest.(check bool)
            ("AC2: no secret keyword '" ^ kw ^ "' in config")
            false
            (contains_str content kw))
        secret_keywords

let test_gemini_run_fails_when_user_settings_blocks_requested_mcp () =
  with_tmpdir (fun dir ->
      let settings_path = Filename.concat dir ".gemini/settings.json" in
      let original = {|{"mcpServers":{"user":{"command":"user-mcp"}}}|} in
      write_file settings_path original ;
      Eio_posix.run @@ fun env ->
      Eio.Switch.run @@ fun sw ->
      let result = Gemini_cli.run_task ~sw ~env (task_spec_with_mcp dir) in
      check_failed_with_mcp_path result ".gemini/settings.json" ;
      Alcotest.(check string)
        "user-authored settings unchanged"
        original
        (read_file settings_path))

let test_gemini_run_fails_when_hash_mismatch_blocks_requested_mcp () =
  with_tmpdir (fun dir ->
      ignore
        (Backend_config_gen.setup_project_config
           ~mcp_servers:[]
           ~backend_id:"gemini-cli"
           ~project_dir:dir
           ~force:false) ;
      let settings_path = Filename.concat dir ".gemini/settings.json" in
      let modified = {|{"mcpServers":{"user":{"command":"modified"}}}|} in
      write_file settings_path modified ;
      Eio_posix.run @@ fun env ->
      Eio.Switch.run @@ fun sw ->
      let result = Gemini_cli.run_task ~sw ~env (task_spec_with_mcp dir) in
      check_failed_with_mcp_path result ".gemini/settings.json" ;
      Alcotest.(check string)
        "hash-mismatched settings unchanged"
        modified
        (read_file settings_path))

(** {1 AC3 — settings artifact is generated} *)

let test_gemini_config_artifact_generated () =
  match Backend_config_gen.generate ~backend_id:"gemini-cli" with
  | None -> Alcotest.fail "AC3: expected settings artifact for gemini-cli"
  | Some a ->
      Alcotest.(check string)
        "AC3: artifact path is .gemini/settings.json"
        ".gemini/settings.json"
        a.Backend_config_gen.project_relative_path

(** {1 AC3 — settings JSON is strict and sidecar-managed} *)

let test_gemini_config_has_managed_marker () =
  match Backend_config_gen.generate ~backend_id:"gemini-cli" with
  | None -> Alcotest.fail "expected artifact for gemini-cli"
  | Some a ->
      Alcotest.(check bool)
        "AC3: settings JSON has no inline epure-managed marker"
        false
        (Backend_config_gen.is_managed_content a.Backend_config_gen.content)

(** {1 AC3 — GEMINI.md is not generated by default} *)

let test_gemini_config_has_project_instructions () =
  let artifacts =
    Backend_config_gen.generate_all ~backend_id:"gemini-cli" ~mcp_servers:[]
  in
  Alcotest.(check bool)
    "AC3: no GEMINI.md artifact is generated"
    false
    (List.exists
       (fun a -> a.Backend_config_gen.project_relative_path = "GEMINI.md")
       artifacts)

let test_gemini_setup_preserves_user_gemini_md () =
  with_tmpdir (fun dir ->
      let path = Filename.concat dir "GEMINI.md" in
      let original = "# Human Gemini Context\n\nKeep this.\n" in
      write_file path original ;
      ignore
        (Backend_config_gen.setup_project_config
           ~mcp_servers:[]
           ~backend_id:"gemini-cli"
           ~project_dir:dir
           ~force:false) ;
      Alcotest.(check string)
        "AC3: user GEMINI.md is unchanged"
        original
        (read_file path))

(** {1 AC3 — settings generation is idempotent} *)

let test_gemini_config_idempotent () =
  match
    ( Backend_config_gen.generate ~backend_id:"gemini-cli",
      Backend_config_gen.generate ~backend_id:"gemini-cli" )
  with
  | None, _ | _, None -> Alcotest.fail "expected artifact for gemini-cli"
  | Some a1, Some a2 ->
      Alcotest.(check string)
        "AC3: two generate calls produce identical content"
        a1.Backend_config_gen.content
        a2.Backend_config_gen.content

(** {1 AC4 — Baseline is the stable version 0.38.2} *)

let test_gemini_baseline_is_stable () =
  let open Backend_registry in
  match find "gemini-cli" with
  | None -> Alcotest.fail "gemini-cli descriptor not found"
  | Some d ->
      Alcotest.(check string)
        "AC4: baseline_version = 0.38.2 (stable)"
        "0.38.2"
        d.baseline_version

(** {1 AC4 — All capability flags match stable upstream for Gemini 0.38.2} *)

let test_gemini_capability_flags_match_baseline () =
  let open Backend_registry in
  match find "gemini-cli" with
  | None -> Alcotest.fail "gemini-cli descriptor not found"
  | Some d ->
      let caps = d.capabilities in
      Alcotest.(check bool)
        "AC4: baseline_version = 0.38.2"
        true
        (d.baseline_version = "0.38.2") ;
      Alcotest.(check bool)
        "AC4: structured_output = true (JSON headless)"
        true
        caps.structured_output ;
      Alcotest.(check bool)
        "AC4: streaming_output = true (stream-json, stable channel)"
        true
        caps.streaming_output ;
      Alcotest.(check bool)
        "AC4: mcp_support = Mcp_user_settings (stable upstream reads \
         settings.json files)"
        true
        (caps.mcp_support = Mcp_user_settings) ;
      Alcotest.(check bool)
        "AC4: project_config_surface = Config_fixed_path \
         (.gemini/settings.json)"
        true
        (caps.project_config_surface = Config_fixed_path) ;
      Alcotest.(check bool)
        "AC4: precedence_confidence = Low (Gemini fixed-path discovery)"
        true
        (caps.precedence_confidence = Low)

(** {1 Suite} *)

let () =
  Alcotest.run
    "Story_482_gemini_parity"
    [
      ( "AC1 JSON and stream-json support",
        [
          Alcotest.test_case
            "structured_output = true (JSON headless)"
            `Quick
            test_gemini_structured_output;
          Alcotest.test_case
            "streaming_output = true (stream-json)"
            `Quick
            test_gemini_streaming_output;
        ] );
      ( "AC2 MCP wired, scoped, no secrets",
        [
          Alcotest.test_case
            "mcp_support = Mcp_user_settings"
            `Quick
            test_gemini_mcp_support_is_user_settings;
          Alcotest.test_case
            "settings contain mcp reference"
            `Quick
            test_gemini_config_contains_mcp_reference;
          Alcotest.test_case
            "settings use workspace path and mcpServers"
            `Quick
            test_gemini_config_points_mcp_to_workspace_settings;
          Alcotest.test_case
            "MCP section is disabled/template-only"
            `Quick
            test_gemini_config_mcp_is_disabled;
          Alcotest.test_case
            "no secret keywords in generated config"
            `Quick
            test_gemini_config_no_secrets;
          Alcotest.test_case
            "requested MCP fails clearly when settings are user-authored"
            `Quick
            test_gemini_run_fails_when_user_settings_blocks_requested_mcp;
          Alcotest.test_case
            "requested MCP fails clearly on settings hash mismatch"
            `Quick
            test_gemini_run_fails_when_hash_mismatch_blocks_requested_mcp;
        ] );
      ( "AC3 Gemini workspace settings strategy",
        [
          Alcotest.test_case
            "artifact generated at .gemini/settings.json path"
            `Quick
            test_gemini_config_artifact_generated;
          Alcotest.test_case
            "settings JSON has no inline managed marker"
            `Quick
            test_gemini_config_has_managed_marker;
          Alcotest.test_case
            "GEMINI.md is not generated by default"
            `Quick
            test_gemini_config_has_project_instructions;
          Alcotest.test_case
            "user GEMINI.md is preserved during setup"
            `Quick
            test_gemini_setup_preserves_user_gemini_md;
          Alcotest.test_case
            "generate is idempotent"
            `Quick
            test_gemini_config_idempotent;
        ] );
      ( "AC4 stable channel only",
        [
          Alcotest.test_case
            "baseline 0.38.2 (stable, not preview/nightly)"
            `Quick
            test_gemini_baseline_is_stable;
          Alcotest.test_case
            "all capability flags match Gemini 0.38.2 stable"
            `Quick
            test_gemini_capability_flags_match_baseline;
        ] );
    ]
